### PR TITLE
Removed official bit

### PR DESCRIPTION
**Pull request by Aditya20-ai**

### CODE REVIEW

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
👋 Please could you provide some context on why you are proposing this change to be made, and why you've made it as three separate pull requests? The wording appears to be fine to me, the linked Discord server is the official server for Project Blurple.

**Comment by Aditya20-ai** [comment]
I understand that we are not affiliated with discord in anyway but the website mentions that we are the Official Project Blurple server multiple times. I'd assume the "official" part was added as a protection against impersonators but we are currently the only Project Blurple server around and we also have a proper website and a decent sized server. I find the official part particularly misleading for new users who might read it and think that we are affiliated with discord, I am aware that its mentioned in the footer but feels like its stressed a lot in the main website itself. 

> why you've made it as three separate pull requests?

Apologies about that, that was my mistake.

**Comment by Aditya20-ai** [comment]
Any updates regarding this PR ?

**Comment by MattIPv4** [comment]
Hey! No updates to speak of currently, just running this by some folks to make sure everyone is on-board with the wording change :)

**Comment by MattIPv4** [comment]
Update to this, after chatting with assorted folks internally, we don't see the need to remove the 'official' wording from the site here -- we've previously combatted other guilds that claim to be a hub for Project Blurple and this wording helps to counter that.

At no point does the wording here imply that this server is an official Discord server from what we can tell, and we want to avoid that for sure, so if you do see any wording that might be misleading in that regard feel free to make an issue or PR to tweak that specific wording. The site attempts to make it clear that this is not affiliated with Discord directly.

**Pull request closed without merging**
